[2025-09-12 07:45:02]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 07:45:05] WARNING django.request - Not Found: /favicon.ico
[2025-09-12 08:04:27]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 08:04:28]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 08:10:06] WARNING django.request - Not Found: /favicon.ico
[2025-09-12 08:36:01]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 08:36:02]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 08:39:27]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 08:39:27]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 08:39:39]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 08:39:40]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 08:41:24]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 08:41:25]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 08:41:27]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 08:41:28]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 08:49:01]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 08:49:01]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 08:50:35]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\urls.py changed, reloading.
[2025-09-12 08:50:35]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 08:50:45]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\urls.py changed, reloading.
[2025-09-12 08:50:46]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 08:53:09]   ERROR django.request - Internal Server Error: /injectionorder/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: '(item.order.order_status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\injectionorder\views.py", line 165, in order_list
    return render(request, 'injectionorder/order_list.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(item.order.order_status' from '(item.order.order_status'
[2025-09-12 09:07:57]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:07:57]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:09:14]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:09:14]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:10:02]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:10:02]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:10:19]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:10:20]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:10:34]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\urls.py changed, reloading.
[2025-09-12 09:10:35]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:11:55]   ERROR django.request - Internal Server Error: /injectionorder/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\injectionorder\views.py", line 131, in order_list
    today = timezone.localdate()
            ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\utils\timezone.py", line 197, in localdate
    return localtime(value, timezone).date()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\utils\timezone.py", line 183, in localtime
    raise ValueError("localtime() cannot be applied to a naive datetime")
ValueError: localtime() cannot be applied to a naive datetime
[2025-09-12 09:14:48]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:14:49]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:15:25]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:15:26]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:16:09]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:16:10]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:16:12]   ERROR django.request - Internal Server Error: /injectionorder/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\injectionorder\views.py", line 128, in order_list
    today = timezone.localdate()
            ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\utils\timezone.py", line 197, in localdate
    return localtime(value, timezone).date()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\utils\timezone.py", line 183, in localtime
    raise ValueError("localtime() cannot be applied to a naive datetime")
ValueError: localtime() cannot be applied to a naive datetime
[2025-09-12 09:16:16]   ERROR django.request - Internal Server Error: /injectionorder/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\injectionorder\views.py", line 128, in order_list
    today = timezone.localdate()
            ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\utils\timezone.py", line 197, in localdate
    return localtime(value, timezone).date()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\utils\timezone.py", line 183, in localtime
    raise ValueError("localtime() cannot be applied to a naive datetime")
ValueError: localtime() cannot be applied to a naive datetime
[2025-09-12 09:17:43]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:17:44]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:17:56]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:17:56]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:18:32]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:18:33]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:18:52]   ERROR django.request - Internal Server Error: /injectionorder/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'localtime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\injectionorder\views.py", line 172, in order_list
    return render(request, 'injectionorder/order_list.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 78: 'localtime', expected 'endblock'. Did you forget to register or load this tag?
[2025-09-12 09:20:01]   ERROR django.request - Internal Server Error: /injectionorder/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\injectionorder\views.py", line 172, in order_list
    return render(request, 'injectionorder/order_list.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 925, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\paginator.py", line 218, in previous_page_number
    return self.paginator.validate_number(self.number - 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\paginator.py", line 69, in validate_number
    raise EmptyPage(self.error_messages["min_page"])
django.core.paginator.EmptyPage: That page number is less than 1
[2025-09-12 09:28:54]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\views.py changed, reloading.
[2025-09-12 09:28:55]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 09:35:54]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, items, order_date, order_lot, order_status, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-12 09:35:57]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, items, order_date, order_lot, order_status, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-12 10:03:42] WARNING django.request - Not Found: /favicon.ico
[2025-09-12 10:32:55]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 10:32:55]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 10:33:10]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 10:33:11]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 10:34:13]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 10:34:13]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 10:35:50]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 10:35:50]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 10:38:20]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 10:38:20]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 10:43:15]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 10:43:15]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 10:45:10]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\injectionorder\models.py changed, reloading.
[2025-09-12 10:45:11]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:27:12]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 11:27:13]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:29:56]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 11:29:57]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:30:16]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 11:30:17]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:30:40]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 11:30:41]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:31:05]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 11:31:06]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:31:24]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\urls.py changed, reloading.
[2025-09-12 11:31:25]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:37:10]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\urls.py changed, reloading.
[2025-09-12 11:37:11]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:37:13]   ERROR django.request - Internal Server Error: /partner/orders/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: '(o.flow_status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(o.flow_status' from '(o.flow_status'
[2025-09-12 11:37:28]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\urls.py changed, reloading.
[2025-09-12 11:37:29]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:42:21]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 11:42:22]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:43:21]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 11:43:22]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 11:52:15]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 11:52:16]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 15:52:30]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\models.py changed, reloading.
[2025-09-12 15:52:31]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 15:54:03]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\urls.py changed, reloading.
[2025-09-12 15:54:04]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 15:54:23]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\urls.py changed, reloading.
[2025-09-12 15:54:23]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 15:54:27]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 15:54:28]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 15:59:40]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\urls.py changed, reloading.
[2025-09-12 15:59:41]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:00:03]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:15:46]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:15:46]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:17:29]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:17:30]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:18:12]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:18:13]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:20:17]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:20:20]   ERROR django.request - Internal Server Error: /partner/orders/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\generic\list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\partnerorder\views.py", line 262, in get_queryset
    for o in qs:
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1937, in _fetch_all
    self._prefetch_related_objects()
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1325, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 2358, in prefetch_related_objects
    raise AttributeError(
AttributeError: Cannot find 'injectionorderitem_set' on InjectionOrder object, 'injectionorderitem_set' is an invalid parameter to prefetch_related()
[2025-09-12 16:20:29]   ERROR django.request - Internal Server Error: /partner/orders/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\generic\list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\partnerorder\views.py", line 262, in get_queryset
    for o in qs:
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1937, in _fetch_all
    self._prefetch_related_objects()
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1325, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 2358, in prefetch_related_objects
    raise AttributeError(
AttributeError: Cannot find 'injectionorderitem_set' on InjectionOrder object, 'injectionorderitem_set' is an invalid parameter to prefetch_related()
[2025-09-12 16:23:45]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:23:46]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:23:57]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:23:57]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:24:23]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:24:23]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:26:09]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:26:09]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:26:26]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:26:26]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:26:41]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:26:42]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:27:05]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:27:06]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 16:27:14]   ERROR django.request - Internal Server Error: /partner/orders/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'print_qr' not found. 'print_qr' is not a valid view function or pattern name.
[2025-09-12 16:37:47]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 16:37:48]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 17:04:11]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 17:04:12]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 17:04:45]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 17:04:46]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 17:06:43]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 17:06:43]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 17:20:46]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\partnerorder\views.py changed, reloading.
[2025-09-12 17:20:46]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-12 17:43:55]   ERROR django.request - Internal Server Error: /quality/incoming/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\quality\views.py", line 20, in incoming_list
    qs = InjectionOrder.objects.filter(status='입고대기', dlt_yn='N').select_related('vendor')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-12 17:45:17]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
